// Mocks generated by Mockito 5.4.4 from annotations
// in feelings/test/features/home/view_models/home_screen_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i9;

import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:feelings/features/auth/models/user_model.dart' as _i6;
import 'package:feelings/features/calendar/models/calendar_event.dart' as _i13;
import 'package:feelings/features/calendar/models/milestone.dart' as _i14;
import 'package:feelings/features/check_in/models/check_in_model.dart' as _i24;
import 'package:feelings/features/check_in/repository/check_in_repository.dart'
    as _i4;
import 'package:feelings/features/date_night/models/date_idea.dart' as _i21;
import 'package:feelings/features/journal/screens/journal_screen.dart' as _i16;
import 'package:feelings/features/questions/models/question_model.dart' as _i11;
import 'package:feelings/features/rhm/models/rhm_action.dart' as _i25;
import 'package:feelings/features/rhm/repository/rhm_repository.dart' as _i19;
import 'package:feelings/providers/bucket_list_provider.dart' as _i17;
import 'package:feelings/providers/calendar_provider.dart' as _i12;
import 'package:feelings/providers/check_in_provider.dart' as _i23;
import 'package:feelings/providers/date_idea_provider.dart' as _i20;
import 'package:feelings/providers/done_dates_provider.dart' as _i18;
import 'package:feelings/providers/journal_provider.dart' as _i15;
import 'package:feelings/providers/question_provider.dart' as _i10;
import 'package:feelings/providers/tips_provider.dart' as _i22;
import 'package:feelings/providers/user_provider.dart' as _i5;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeImageProvider_0<T extends Object> extends _i1.SmartFake
    implements _i2.ImageProvider<T> {
  _FakeImageProvider_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentReference_1<T extends Object?> extends _i1.SmartFake
    implements _i3.DocumentReference<T> {
  _FakeDocumentReference_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCheckInRepository_2 extends _i1.SmartFake
    implements _i4.CheckInRepository {
  _FakeCheckInRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProvider extends _i1.Mock implements _i5.UserProvider {
  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setCurrentUser(_i6.UserModel? user) => super.noSuchMethod(
        Invocation.method(
          #setCurrentUser,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> fetchUserData() => (super.noSuchMethod(
        Invocation.method(
          #fetchUserData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateProfileImage(String? newImageUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfileImage,
          [newImageUrl],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.ImageProvider<Object>> getProfileImage() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileImage,
          [],
        ),
        returnValue: _i7.Future<_i2.ImageProvider<Object>>.value(
            _FakeImageProvider_0<Object>(
          this,
          Invocation.method(
            #getProfileImage,
            [],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i2.ImageProvider<Object>>.value(
            _FakeImageProvider_0<Object>(
          this,
          Invocation.method(
            #getProfileImage,
            [],
          ),
        )),
      ) as _i7.Future<_i2.ImageProvider<Object>>);

  @override
  _i2.ImageProvider<Object> getProfileImageSync() => (super.noSuchMethod(
        Invocation.method(
          #getProfileImageSync,
          [],
        ),
        returnValue: _FakeImageProvider_0<Object>(
          this,
          Invocation.method(
            #getProfileImageSync,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeImageProvider_0<Object>(
          this,
          Invocation.method(
            #getProfileImageSync,
            [],
          ),
        ),
      ) as _i2.ImageProvider<Object>);

  @override
  _i7.Future<_i2.ImageProvider<Object>> getPartnerProfileImage() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPartnerProfileImage,
          [],
        ),
        returnValue: _i7.Future<_i2.ImageProvider<Object>>.value(
            _FakeImageProvider_0<Object>(
          this,
          Invocation.method(
            #getPartnerProfileImage,
            [],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i2.ImageProvider<Object>>.value(
            _FakeImageProvider_0<Object>(
          this,
          Invocation.method(
            #getPartnerProfileImage,
            [],
          ),
        )),
      ) as _i7.Future<_i2.ImageProvider<Object>>);

  @override
  _i2.ImageProvider<Object> getPartnerProfileImageSync() => (super.noSuchMethod(
        Invocation.method(
          #getPartnerProfileImageSync,
          [],
        ),
        returnValue: _FakeImageProvider_0<Object>(
          this,
          Invocation.method(
            #getPartnerProfileImageSync,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeImageProvider_0<Object>(
          this,
          Invocation.method(
            #getPartnerProfileImageSync,
            [],
          ),
        ),
      ) as _i2.ImageProvider<Object>);

  @override
  _i7.Future<void> fetchPartnerData() => (super.noSuchMethod(
        Invocation.method(
          #fetchPartnerData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void listenToPartnerMood(String? partnerId) => super.noSuchMethod(
        Invocation.method(
          #listenToPartnerMood,
          [partnerId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopListeningToPartner() => super.noSuchMethod(
        Invocation.method(
          #stopListeningToPartner,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> authenticateWithSharedPreferences() => (super.noSuchMethod(
        Invocation.method(
          #authenticateWithSharedPreferences,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveUserIdToSharedPreferences(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserIdToSharedPreferences,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserData(Map<String, dynamic>? updatedFields) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserData,
          [updatedFields],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserMood(String? mood) => (super.noSuchMethod(
        Invocation.method(
          #updateUserMood,
          [mood],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteCurrentUserAccount(String? password) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCurrentUserAccount,
          [password],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateFcmToken(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #updateFcmToken,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> refreshFcmToken(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #refreshFcmToken,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> manuallyRefreshFcmToken() => (super.noSuchMethod(
        Invocation.method(
          #manuallyRefreshFcmToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
        returnValueForMissingStub: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<Map<String, dynamic>> checkFcmStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkFcmStatus,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> testFcmNotification() => (super.noSuchMethod(
        Invocation.method(
          #testFcmNotification,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendPushNotification(
    String? receiverId,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPushNotification,
          [
            receiverId,
            message,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> getCoupleId() => (super.noSuchMethod(
        Invocation.method(
          #getCoupleId,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserLocation(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserLocation,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String> generateAndAssignCoupleCode(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAndAssignCoupleCode,
          [userId],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateAndAssignCoupleCode,
            [userId],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateAndAssignCoupleCode,
            [userId],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> updateUserLoveLanguage(String? loveLanguage) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserLoveLanguage,
          [loveLanguage],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserGender(_i6.Gender? gender) => (super.noSuchMethod(
        Invocation.method(
          #updateUserGender,
          [gender],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [QuestionProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuestionProvider extends _i1.Mock implements _i10.QuestionProvider {
  @override
  List<_i11.QuestionModel> get availableQuestions => (super.noSuchMethod(
        Invocation.getter(#availableQuestions),
        returnValue: <_i11.QuestionModel>[],
        returnValueForMissingStub: <_i11.QuestionModel>[],
      ) as List<_i11.QuestionModel>);

  @override
  List<_i11.QuestionModel> get questions => (super.noSuchMethod(
        Invocation.getter(#questions),
        returnValue: <_i11.QuestionModel>[],
        returnValueForMissingStub: <_i11.QuestionModel>[],
      ) as List<_i11.QuestionModel>);

  @override
  List<String> get doneQuestions => (super.noSuchMethod(
        Invocation.getter(#doneQuestions),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<String> get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  bool get isLoadingDailyQuestion => (super.noSuchMethod(
        Invocation.getter(#isLoadingDailyQuestion),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<String> getSubCategoriesForCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubCategoriesForCategory,
          [category],
        ),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  _i7.Future<void> fetchQuestions(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #fetchQuestions,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchDailyQuestion(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #fetchDailyQuestion,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchQuestionsByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchQuestionsByCategory,
          [category],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchQuestionsBySubCategory(String? subCategory) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchQuestionsBySubCategory,
          [subCategory],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchQuestionsByCategoryAndSubCategory(
    String? category,
    String? subCategory,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchQuestionsByCategoryAndSubCategory,
          [
            category,
            subCategory,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markQuestionAsDone(
    String? userId,
    String? questionId,
    String? coupleId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markQuestionAsDone,
          [
            userId,
            questionId,
            coupleId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeQuestionFromDone(
    String? userId,
    String? questionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeQuestionFromDone,
          [
            userId,
            questionId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> countDoneQuestions(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #countDoneQuestions,
          [userId],
        ),
        returnValue: _i7.Future<int>.value(0),
        returnValueForMissingStub: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> fetchRandomAvailableQuestion(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRandomAvailableQuestion,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchRandomAvailableQuestionByCategory(
    String? userId,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRandomAvailableQuestionByCategory,
          [
            userId,
            category,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchRandomAvailableQuestionBySubCategory(
    String? userId,
    String? subCategory,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRandomAvailableQuestionBySubCategory,
          [
            userId,
            subCategory,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchRandomAvailableQuestionByCategoryAndSubCategory(
    String? userId,
    String? category,
    String? subCategory,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRandomAvailableQuestionByCategoryAndSubCategory,
          [
            userId,
            category,
            subCategory,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void clearCurrentRandomQuestion() => super.noSuchMethod(
        Invocation.method(
          #clearCurrentRandomQuestion,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> refreshCategoriesAndSubCategories() => (super.noSuchMethod(
        Invocation.method(
          #refreshCategoriesAndSubCategories,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CalendarProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarProvider extends _i1.Mock implements _i12.CalendarProvider {
  @override
  List<_i13.CalendarEvent> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: <_i13.CalendarEvent>[],
        returnValueForMissingStub: <_i13.CalendarEvent>[],
      ) as List<_i13.CalendarEvent>);

  @override
  List<_i13.CalendarEvent> get allEvents => (super.noSuchMethod(
        Invocation.getter(#allEvents),
        returnValue: <_i13.CalendarEvent>[],
        returnValueForMissingStub: <_i13.CalendarEvent>[],
      ) as List<_i13.CalendarEvent>);

  @override
  List<_i14.Milestone> get milestones => (super.noSuchMethod(
        Invocation.getter(#milestones),
        returnValue: <_i14.Milestone>[],
        returnValueForMissingStub: <_i14.Milestone>[],
      ) as List<_i14.Milestone>);

  @override
  bool get milestonesLoading => (super.noSuchMethod(
        Invocation.getter(#milestonesLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCurrentUserId(String? userId) => super.noSuchMethod(
        Invocation.method(
          #setCurrentUserId,
          [userId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToEvents(String? coupleId) => super.noSuchMethod(
        Invocation.method(
          #listenToEvents,
          [coupleId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToMilestones(String? coupleId) => super.noSuchMethod(
        Invocation.method(
          #listenToMilestones,
          [coupleId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<String> addEvent(
    String? coupleId,
    Map<String, dynamic>? eventData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEvent,
          [
            coupleId,
            eventData,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #addEvent,
            [
              coupleId,
              eventData,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #addEvent,
            [
              coupleId,
              eventData,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> updateEvent(
    String? coupleId,
    String? eventId,
    Map<String, dynamic>? eventData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEvent,
          [
            coupleId,
            eventId,
            eventData,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteEvent(
    String? coupleId,
    String? eventId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [
            coupleId,
            eventId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> countUpcomingEvents() => (super.noSuchMethod(
        Invocation.method(
          #countUpcomingEvents,
          [],
        ),
        returnValue: _i7.Future<int>.value(0),
        returnValueForMissingStub: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  List<_i13.CalendarEvent> getUpcomingReminders({int? limit = 3}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingReminders,
          [],
          {#limit: limit},
        ),
        returnValue: <_i13.CalendarEvent>[],
        returnValueForMissingStub: <_i13.CalendarEvent>[],
      ) as List<_i13.CalendarEvent>);

  @override
  List<_i13.CalendarEvent> getUpcomingEvents({int? limit = 3}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEvents,
          [],
          {#limit: limit},
        ),
        returnValue: <_i13.CalendarEvent>[],
        returnValueForMissingStub: <_i13.CalendarEvent>[],
      ) as List<_i13.CalendarEvent>);

  @override
  _i7.Future<String> addMilestone(
    String? coupleId,
    Map<String, dynamic>? milestoneData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMilestone,
          [
            coupleId,
            milestoneData,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #addMilestone,
            [
              coupleId,
              milestoneData,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #addMilestone,
            [
              coupleId,
              milestoneData,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> updateMilestone(
    String? coupleId,
    String? milestoneId,
    Map<String, dynamic>? milestoneData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMilestone,
          [
            coupleId,
            milestoneId,
            milestoneData,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteMilestone(
    String? coupleId,
    String? milestoneId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMilestone,
          [
            coupleId,
            milestoneId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [JournalProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalProvider extends _i1.Mock implements _i15.JournalProvider {
  @override
  set filterToShowOnNextLoad(
          _i16.JournalFilterOption? _filterToShowOnNextLoad) =>
      super.noSuchMethod(
        Invocation.setter(
          #filterToShowOnNextLoad,
          _filterToShowOnNextLoad,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get showAddMemoryOnNextLoad => (super.noSuchMethod(
        Invocation.getter(#showAddMemoryOnNextLoad),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set showAddMemoryOnNextLoad(bool? _showAddMemoryOnNextLoad) =>
      super.noSuchMethod(
        Invocation.setter(
          #showAddMemoryOnNextLoad,
          _showAddMemoryOnNextLoad,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<Map<String, dynamic>> get personalEntries => (super.noSuchMethod(
        Invocation.getter(#personalEntries),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>> get sharedEntries => (super.noSuchMethod(
        Invocation.getter(#sharedEntries),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToPersonalJournals(String? userId) => super.noSuchMethod(
        Invocation.method(
          #listenToPersonalJournals,
          [userId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i3.DocumentReference<Object?>> addPersonalJournalEntry(
    String? userId,
    Map<String, dynamic>? entryData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPersonalJournalEntry,
          [
            userId,
            entryData,
          ],
        ),
        returnValue: _i7.Future<_i3.DocumentReference<Object?>>.value(
            _FakeDocumentReference_1<Object?>(
          this,
          Invocation.method(
            #addPersonalJournalEntry,
            [
              userId,
              entryData,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i3.DocumentReference<Object?>>.value(
                _FakeDocumentReference_1<Object?>(
          this,
          Invocation.method(
            #addPersonalJournalEntry,
            [
              userId,
              entryData,
            ],
          ),
        )),
      ) as _i7.Future<_i3.DocumentReference<Object?>>);

  @override
  _i7.Future<void> updatePersonalJournalEntry(
    String? userId,
    String? entryId,
    Map<String, dynamic>? entryData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePersonalJournalEntry,
          [
            userId,
            entryId,
            entryData,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deletePersonalJournal(
    String? userId,
    String? journalId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePersonalJournal,
          [
            userId,
            journalId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> getTotalPersonalJournals(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalPersonalJournals,
          [userId],
        ),
        returnValue: _i7.Future<int>.value(0),
        returnValueForMissingStub: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  void listenToSharedJournals(String? coupleId) => super.noSuchMethod(
        Invocation.method(
          #listenToSharedJournals,
          [coupleId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i3.DocumentReference<Object?>> addSharedJournalEntry(
    String? coupleId,
    Map<String, dynamic>? entryData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSharedJournalEntry,
          [
            coupleId,
            entryData,
          ],
        ),
        returnValue: _i7.Future<_i3.DocumentReference<Object?>>.value(
            _FakeDocumentReference_1<Object?>(
          this,
          Invocation.method(
            #addSharedJournalEntry,
            [
              coupleId,
              entryData,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i3.DocumentReference<Object?>>.value(
                _FakeDocumentReference_1<Object?>(
          this,
          Invocation.method(
            #addSharedJournalEntry,
            [
              coupleId,
              entryData,
            ],
          ),
        )),
      ) as _i7.Future<_i3.DocumentReference<Object?>>);

  @override
  _i7.Future<void> updateSharedJournalEntry(
    String? coupleId,
    String? userId,
    String? entryId,
    Map<String, dynamic>? entryData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSharedJournalEntry,
          [
            coupleId,
            userId,
            entryId,
            entryData,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteSharedJournalSegment(
    String? coupleId,
    String? entryId,
    int? segmentIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSharedJournalSegment,
          [
            coupleId,
            entryId,
            segmentIndex,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteSharedJournalEntry(
    String? coupleId,
    String? entryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSharedJournalEntry,
          [
            coupleId,
            entryId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void setNextJournalFilter(_i16.JournalFilterOption? filter) =>
      super.noSuchMethod(
        Invocation.method(
          #setNextJournalFilter,
          [filter],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setNextShowAddMemory() => super.noSuchMethod(
        Invocation.method(
          #setNextShowAddMemory,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCommands() => super.noSuchMethod(
        Invocation.method(
          #clearCommands,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BucketListProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockBucketListProvider extends _i1.Mock
    implements _i17.BucketListProvider {
  @override
  List<Map<String, dynamic>> get bucketList => (super.noSuchMethod(
        Invocation.getter(#bucketList),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get sortBy => (super.noSuchMethod(
        Invocation.getter(#sortBy),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#sortBy),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#sortBy),
        ),
      ) as String);

  @override
  String get filterBy => (super.noSuchMethod(
        Invocation.getter(#filterBy),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#filterBy),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#filterBy),
        ),
      ) as String);

  @override
  bool get showCompleted => (super.noSuchMethod(
        Invocation.getter(#showCompleted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<Map<String, dynamic>> get filteredBucketList => (super.noSuchMethod(
        Invocation.getter(#filteredBucketList),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setDoneDatesProvider(_i18.DoneDatesProvider? provider) =>
      super.noSuchMethod(
        Invocation.method(
          #setDoneDatesProvider,
          [provider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> initialize({
    required String? coupleId,
    required String? userId,
    required _i19.RhmRepository? rhmRepository,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #coupleId: coupleId,
            #userId: userId,
            #rhmRepository: rhmRepository,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> resetPreferences() => (super.noSuchMethod(
        Invocation.method(
          #resetPreferences,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  Map<String, dynamic> getCurrentPreferences() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPreferences,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i7.Future<void> addItem(
    String? title, {
    bool? isDateIdea = false,
    String? dateId,
    String? description,
    String? category,
    List<String>? whatYoullNeed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [title],
          {
            #isDateIdea: isDateIdea,
            #dateId: dateId,
            #description: description,
            #category: category,
            #whatYoullNeed: whatYoullNeed,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> toggleItemCompletion(
    String? itemId,
    bool? completed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleItemCompletion,
          [
            itemId,
            completed,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteItem(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [itemId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateItem(
    String? itemId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [
            itemId,
            data,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> getUncheckedCount() => (super.noSuchMethod(
        Invocation.method(
          #getUncheckedCount,
          [],
        ),
        returnValue: _i7.Future<int>.value(0),
        returnValueForMissingStub: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Stream<List<Map<String, dynamic>>> searchItems(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchItems,
          [query],
        ),
        returnValue: _i7.Stream<List<Map<String, dynamic>>>.empty(),
        returnValueForMissingStub:
            _i7.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i7.Stream<List<Map<String, dynamic>>>);

  @override
  void setSortBy(String? value) => super.noSuchMethod(
        Invocation.method(
          #setSortBy,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFilterBy(String? value) => super.noSuchMethod(
        Invocation.method(
          #setFilterBy,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setShowCompleted(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setShowCompleted,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DoneDatesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoneDatesProvider extends _i1.Mock implements _i18.DoneDatesProvider {
  @override
  List<Map<String, dynamic>> get doneDates => (super.noSuchMethod(
        Invocation.getter(#doneDates),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isRepositoryInitialized => (super.noSuchMethod(
        Invocation.getter(#isRepositoryInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isValidationTimerRunning => (super.noSuchMethod(
        Invocation.getter(#isValidationTimerRunning),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void initializeRepository(String? coupleId) => super.noSuchMethod(
        Invocation.method(
          #initializeRepository,
          [coupleId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> getDoneDatesCount(String? coupleId) => (super.noSuchMethod(
        Invocation.method(
          #getDoneDatesCount,
          [coupleId],
        ),
        returnValue: _i7.Future<int>.value(0),
        returnValueForMissingStub: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> addDoneDateFromSuggestion({
    required String? dateIdeaId,
    required String? title,
    required String? description,
    required String? suggestionId,
    required String? completedBy,
    DateTime? actualDate,
    String? notes,
    int? rating,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDoneDateFromSuggestion,
          [],
          {
            #dateIdeaId: dateIdeaId,
            #title: title,
            #description: description,
            #suggestionId: suggestionId,
            #completedBy: completedBy,
            #actualDate: actualDate,
            #notes: notes,
            #rating: rating,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addDoneDateFromCalendar({
    required String? dateIdeaId,
    required String? title,
    required String? description,
    required String? eventId,
    required String? completedBy,
    required DateTime? eventDate,
    String? notes,
    int? rating,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDoneDateFromCalendar,
          [],
          {
            #dateIdeaId: dateIdeaId,
            #title: title,
            #description: description,
            #eventId: eventId,
            #completedBy: completedBy,
            #eventDate: eventDate,
            #notes: notes,
            #rating: rating,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addDoneDateFromBucketList({
    required String? dateIdeaId,
    required String? title,
    required String? description,
    required String? bucketListItemId,
    required String? completedBy,
    DateTime? actualDate,
    String? notes,
    int? rating,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDoneDateFromBucketList,
          [],
          {
            #dateIdeaId: dateIdeaId,
            #title: title,
            #description: description,
            #bucketListItemId: bucketListItemId,
            #completedBy: completedBy,
            #actualDate: actualDate,
            #notes: notes,
            #rating: rating,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateDoneDate(
    String? doneDateId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDoneDate,
          [
            doneDateId,
            updates,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteDoneDate(String? doneDateId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDoneDate,
          [doneDateId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isDateIdeaCompleted(String? dateIdeaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDateIdeaCompleted,
          [dateIdeaId],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  List<Map<String, dynamic>> getDoneDatesBySource(String? source) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDoneDatesBySource,
          [source],
        ),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> validatePassedCalendarEvents() => (super.noSuchMethod(
        Invocation.method(
          #validatePassedCalendarEvents,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> forceValidateAllCalendarEvents() => (super.noSuchMethod(
        Invocation.method(
          #forceValidateAllCalendarEvents,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<Map<String, dynamic>> getRecentDoneDates() => (super.noSuchMethod(
        Invocation.method(
          #getRecentDoneDates,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>> getDoneDatesForMonth(
    int? year,
    int? month,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDoneDatesForMonth,
          [
            year,
            month,
          ],
        ),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DateIdeaProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateIdeaProvider extends _i1.Mock implements _i20.DateIdeaProvider {
  @override
  List<_i21.DateIdea> get favoriteIdeas => (super.noSuchMethod(
        Invocation.getter(#favoriteIdeas),
        returnValue: <_i21.DateIdea>[],
        returnValueForMissingStub: <_i21.DateIdea>[],
      ) as List<_i21.DateIdea>);

  @override
  set favoriteIdeas(List<_i21.DateIdea>? _favoriteIdeas) => super.noSuchMethod(
        Invocation.setter(
          #favoriteIdeas,
          _favoriteIdeas,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isFavoritesLoading => (super.noSuchMethod(
        Invocation.getter(#isFavoritesLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isFavoritesLoading(bool? _isFavoritesLoading) => super.noSuchMethod(
        Invocation.setter(
          #isFavoritesLoading,
          _isFavoritesLoading,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> get selectedLocations => (super.noSuchMethod(
        Invocation.getter(#selectedLocations),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  set selectedLocations(List<String>? _selectedLocations) => super.noSuchMethod(
        Invocation.setter(
          #selectedLocations,
          _selectedLocations,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedVibe(String? _selectedVibe) => super.noSuchMethod(
        Invocation.setter(
          #selectedVibe,
          _selectedVibe,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedBudget(String? _selectedBudget) => super.noSuchMethod(
        Invocation.setter(
          #selectedBudget,
          _selectedBudget,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedTime(String? _selectedTime) => super.noSuchMethod(
        Invocation.setter(
          #selectedTime,
          _selectedTime,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set generatedIdea(_i21.DateIdea? _generatedIdea) => super.noSuchMethod(
        Invocation.setter(
          #generatedIdea,
          _generatedIdea,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isLoading(bool? _isLoading) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          _isLoading,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentSuggestionId(String? _currentSuggestionId) => super.noSuchMethod(
        Invocation.setter(
          #currentSuggestionId,
          _currentSuggestionId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentSuggestionCoupleId(String? _currentSuggestionCoupleId) =>
      super.noSuchMethod(
        Invocation.setter(
          #currentSuggestionCoupleId,
          _currentSuggestionCoupleId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentSuggestionIdeaId(String? _currentSuggestionIdeaId) =>
      super.noSuchMethod(
        Invocation.setter(
          #currentSuggestionIdeaId,
          _currentSuggestionIdeaId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set fallbackMessage(String? _fallbackMessage) => super.noSuchMethod(
        Invocation.setter(
          #fallbackMessage,
          _fallbackMessage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get disposed => (super.noSuchMethod(
        Invocation.getter(#disposed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set disposed(bool? _disposed) => super.noSuchMethod(
        Invocation.setter(
          #disposed,
          _disposed,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<Map<String, dynamic>> get suggestions => (super.noSuchMethod(
        Invocation.getter(#suggestions),
        returnValue: <Map<String, dynamic>>[],
        returnValueForMissingStub: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  bool get isStreamConnected => (super.noSuchMethod(
        Invocation.getter(#isStreamConnected),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void updateDependencies(_i18.DoneDatesProvider? doneDatesProvider) =>
      super.noSuchMethod(
        Invocation.method(
          #updateDependencies,
          [doneDatesProvider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToSuggestions(String? coupleId) => super.noSuchMethod(
        Invocation.method(
          #listenToSuggestions,
          [coupleId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> refreshSuggestions() => (super.noSuchMethod(
        Invocation.method(
          #refreshSuggestions,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void clearSuggestionTracking() => super.noSuchMethod(
        Invocation.method(
          #clearSuggestionTracking,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isCurrentSuggestion(String? ideaId) => (super.noSuchMethod(
        Invocation.method(
          #isCurrentSuggestion,
          [ideaId],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setCurrentSuggestion(
    String? suggestionId,
    String? coupleId,
    String? ideaId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setCurrentSuggestion,
          [
            suggestionId,
            coupleId,
            ideaId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void debugSuggestionState() => super.noSuchMethod(
        Invocation.method(
          #debugSuggestionState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> testStreamConnection() => (super.noSuchMethod(
        Invocation.method(
          #testStreamConnection,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i21.DateIdea?> getDateIdeaById(String? dateIdeaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDateIdeaById,
          [dateIdeaId],
        ),
        returnValue: _i7.Future<_i21.DateIdea?>.value(),
        returnValueForMissingStub: _i7.Future<_i21.DateIdea?>.value(),
      ) as _i7.Future<_i21.DateIdea?>);

  @override
  _i7.Future<void> suggestDateIdeaToPartner({
    required _i21.DateIdea? idea,
    required String? coupleId,
    required String? currentUserId,
    required String? partnerId,
    required _i7.Future<void> Function(
      String,
      String,
    )? sendPushNotification,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #suggestDateIdeaToPartner,
          [],
          {
            #idea: idea,
            #coupleId: coupleId,
            #currentUserId: currentUserId,
            #partnerId: partnerId,
            #sendPushNotification: sendPushNotification,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markSuggestionAsDone(
    String? coupleId,
    String? suggestionId,
    String? currentUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markSuggestionAsDone,
          [
            coupleId,
            suggestionId,
            currentUserId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cancelSuggestion({
    required String? coupleId,
    required String? suggestionId,
    required String? currentUserId,
    required String? partnerId,
    required _i7.Future<void> Function(
      String,
      String,
    )? sendPushNotification,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelSuggestion,
          [],
          {
            #coupleId: coupleId,
            #suggestionId: suggestionId,
            #currentUserId: currentUserId,
            #partnerId: partnerId,
            #sendPushNotification: sendPushNotification,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void toggleLocation(String? location) => super.noSuchMethod(
        Invocation.method(
          #toggleLocation,
          [location],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectVibe(String? vibe) => super.noSuchMethod(
        Invocation.method(
          #selectVibe,
          [vibe],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectBudget(String? budget) => super.noSuchMethod(
        Invocation.method(
          #selectBudget,
          [budget],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectTime(String? time) => super.noSuchMethod(
        Invocation.method(
          #selectTime,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> generateDateIdea({
    required String? userId,
    required String? coupleId,
    _i2.BuildContext? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateDateIdea,
          [],
          {
            #userId: userId,
            #coupleId: coupleId,
            #context: context,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFilters({
    List<String>? locations,
    String? vibe,
    String? budget,
    String? time,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setFilters,
          [],
          {
            #locations: locations,
            #vibe: vibe,
            #budget: budget,
            #time: time,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> addFavorite(
    _i21.DateIdea? idea,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [
            idea,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeFavorite(
    String? ideaId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [
            ideaId,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchFavorites(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #fetchFavorites,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool isFavorite(String? ideaId) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [ideaId],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TipsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTipsProvider extends _i1.Mock implements _i22.TipsProvider {
  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> initialize({
    required String? userId,
    required String? coupleId,
    required Map<String, dynamic>? userData,
    required Map<String, dynamic>? partnerData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #userId: userId,
            #coupleId: coupleId,
            #userData: userData,
            #partnerData: partnerData,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserContext({
    Map<String, dynamic>? userData,
    Map<String, dynamic>? partnerData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserContext,
          [],
          {
            #userData: userData,
            #partnerData: partnerData,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CheckInProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckInProvider extends _i1.Mock implements _i23.CheckInProvider {
  @override
  List<_i24.CheckInModel> get checkInHistory => (super.noSuchMethod(
        Invocation.getter(#checkInHistory),
        returnValue: <_i24.CheckInModel>[],
        returnValueForMissingStub: <_i24.CheckInModel>[],
      ) as List<_i24.CheckInModel>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.CheckInRepository get checkInRepository => (super.noSuchMethod(
        Invocation.getter(#checkInRepository),
        returnValue: _FakeCheckInRepository_2(
          this,
          Invocation.getter(#checkInRepository),
        ),
        returnValueForMissingStub: _FakeCheckInRepository_2(
          this,
          Invocation.getter(#checkInRepository),
        ),
      ) as _i4.CheckInRepository);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<String?> createCheckIn(
    String? userId,
    String? coupleId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCheckIn,
          [
            userId,
            coupleId,
          ],
        ),
        returnValue: _i7.Future<String?>.value(),
        returnValueForMissingStub: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> fetchLatestPartnerInsight(
    String? currentUserId,
    String? partnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchLatestPartnerInsight,
          [
            currentUserId,
            partnerId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markInsightAsRead(
    String? currentUserId,
    String? checkInId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markInsightAsRead,
          [
            currentUserId,
            checkInId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> loadCheckIn(
    String? userId,
    String? checkInId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadCheckIn,
          [
            userId,
            checkInId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> completeCheckIn(
    String? userId,
    String? checkInId,
    String? coupleId,
    List<_i24.CheckInQuestion>? questions,
    Map<String, dynamic>? answers,
    String? partnerId, {
    dynamic Function(
      String,
      String,
    )? sendPushNotification,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeCheckIn,
          [
            userId,
            checkInId,
            coupleId,
            questions,
            answers,
            partnerId,
          ],
          {#sendPushNotification: sendPushNotification},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> shareInsights(
    String? userId,
    String? checkInId,
    List<String>? insights,
    String? coupleId, {
    String? partnerFirstName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareInsights,
          [
            userId,
            checkInId,
            insights,
            coupleId,
          ],
          {#partnerFirstName: partnerFirstName},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setReminder(
    String? userId,
    String? checkInId,
    bool? reminderSet,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReminder,
          [
            userId,
            checkInId,
            reminderSet,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>> getStats(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [userId],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i24.CheckInModel?> getLastCompletedCheckIn(
    String? userId, {
    String? partnerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastCompletedCheckIn,
          [userId],
          {#partnerId: partnerId},
        ),
        returnValue: _i7.Future<_i24.CheckInModel?>.value(),
        returnValueForMissingStub: _i7.Future<_i24.CheckInModel?>.value(),
      ) as _i7.Future<_i24.CheckInModel?>);

  @override
  _i7.Stream<_i3.QuerySnapshot<Map<String, dynamic>>> getUserCheckInsStream(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserCheckInsStream,
          [userId],
        ),
        returnValue:
            _i7.Stream<_i3.QuerySnapshot<Map<String, dynamic>>>.empty(),
        returnValueForMissingStub:
            _i7.Stream<_i3.QuerySnapshot<Map<String, dynamic>>>.empty(),
      ) as _i7.Stream<_i3.QuerySnapshot<Map<String, dynamic>>>);

  @override
  void clearCurrentCheckIn() => super.noSuchMethod(
        Invocation.method(
          #clearCurrentCheckIn,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> generateInsights(
    _i24.CheckInModel? checkIn, {
    List<_i24.CheckInModel>? recentHistory,
    bool? forPartner = false,
    String? userName,
    String? partnerName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateInsights,
          [checkIn],
          {
            #recentHistory: recentHistory,
            #forPartner: forPartner,
            #userName: userName,
            #partnerName: partnerName,
          },
        ),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  _i7.Future<void> shareFullCheckInWithPartner(
    String? userId,
    String? partnerId,
    String? checkInId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareFullCheckInWithPartner,
          [
            userId,
            partnerId,
            checkInId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void listenToLatestPartnerInsight(
    String? currentUserId,
    String? partnerId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToLatestPartnerInsight,
          [
            currentUserId,
            partnerId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> cancelCheckIn(
    String? userId,
    String? checkInId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelCheckIn,
          [
            userId,
            checkInId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> shareSelectedInsights({
    required String? userId,
    required String? partnerId,
    required String? coupleId,
    required List<String>? insights,
    required String? checkInId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareSelectedInsights,
          [],
          {
            #userId: userId,
            #partnerId: partnerId,
            #coupleId: coupleId,
            #insights: insights,
            #checkInId: checkInId,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RhmRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRhmRepository extends _i1.Mock implements _i19.RhmRepository {
  @override
  _i7.Future<void> logAction({
    required String? coupleId,
    required String? userId,
    required String? actionType,
    required int? points,
    String? sourceId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logAction,
          [],
          {
            #coupleId: coupleId,
            #userId: userId,
            #actionType: actionType,
            #points: points,
            #sourceId: sourceId,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Stream<int> getRhmScoreStream(String? coupleId) => (super.noSuchMethod(
        Invocation.method(
          #getRhmScoreStream,
          [coupleId],
        ),
        returnValue: _i7.Stream<int>.empty(),
        returnValueForMissingStub: _i7.Stream<int>.empty(),
      ) as _i7.Stream<int>);

  @override
  _i7.Stream<List<_i25.RhmAction>> getRecentActionsStream(String? coupleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentActionsStream,
          [coupleId],
        ),
        returnValue: _i7.Stream<List<_i25.RhmAction>>.empty(),
        returnValueForMissingStub: _i7.Stream<List<_i25.RhmAction>>.empty(),
      ) as _i7.Stream<List<_i25.RhmAction>>);

  @override
  _i7.Future<DateTime?> getLastActionTimestamp(
    String? coupleId,
    String? actionType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastActionTimestamp,
          [
            coupleId,
            actionType,
          ],
        ),
        returnValue: _i7.Future<DateTime?>.value(),
        returnValueForMissingStub: _i7.Future<DateTime?>.value(),
      ) as _i7.Future<DateTime?>);

  @override
  _i7.Future<DateTime?> getLastActionTimestampForUser(
    String? coupleId,
    String? userId,
    String? actionType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastActionTimestampForUser,
          [
            coupleId,
            userId,
            actionType,
          ],
        ),
        returnValue: _i7.Future<DateTime?>.value(),
        returnValueForMissingStub: _i7.Future<DateTime?>.value(),
      ) as _i7.Future<DateTime?>);
}
