// Mocks generated by Mockito 5.4.4 from annotations
// in feelings/test/features/home/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i16;
import 'dart:ui' as _i8;

import 'package:cloud_firestore/cloud_firestore.dart' as _i14;
import 'package:feelings/features/auth/models/user_model.dart' as _i10;
import 'package:feelings/features/calendar/models/calendar_event.dart' as _i5;
import 'package:feelings/features/check_in/models/check_in_model.dart' as _i13;
import 'package:feelings/features/check_in/repository/check_in_repository.dart'
    as _i4;
import 'package:feelings/features/date_night/models/date_idea.dart' as _i19;
import 'package:feelings/features/home/models/quick_action_model.dart' as _i22;
import 'package:feelings/features/home/view_models/home_screen_view_model.dart'
    as _i2;
import 'package:feelings/features/rhm/models/rhm_action.dart' as _i24;
import 'package:feelings/providers/check_in_provider.dart' as _i12;
import 'package:feelings/providers/couple_provider.dart' as _i11;
import 'package:feelings/providers/date_idea_provider.dart' as _i18;
import 'package:feelings/providers/done_dates_provider.dart' as _i20;
import 'package:feelings/providers/dynamic_actions_provider.dart' as _i21;
import 'package:feelings/providers/rhm_detail_provider.dart' as _i23;
import 'package:feelings/providers/secret_note_provider.dart' as _i15;
import 'package:feelings/providers/tips_provider.dart' as _i17;
import 'package:feelings/providers/user_provider.dart' as _i9;
import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeScreenStats_0 extends _i1.SmartFake
    implements _i2.HomeScreenStats {
  _FakeHomeScreenStats_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageProvider_1<T extends Object> extends _i1.SmartFake
    implements _i3.ImageProvider<T> {
  _FakeImageProvider_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCheckInRepository_2 extends _i1.SmartFake
    implements _i4.CheckInRepository {
  _FakeCheckInRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeScreenViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeScreenViewModel extends _i1.Mock
    implements _i2.HomeScreenViewModel {
  MockHomeScreenViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeScreenStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i2.HomeScreenStatus.loading,
      ) as _i2.HomeScreenStatus);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  List<_i5.CalendarEvent> get upcomingEvents => (super.noSuchMethod(
        Invocation.getter(#upcomingEvents),
        returnValue: <_i5.CalendarEvent>[],
      ) as List<_i5.CalendarEvent>);

  @override
  _i2.HomeScreenStats get stats => (super.noSuchMethod(
        Invocation.getter(#stats),
        returnValue: _FakeHomeScreenStats_0(
          this,
          Invocation.getter(#stats),
        ),
      ) as _i2.HomeScreenStats);

  @override
  String get errorMessage => (super.noSuchMethod(
        Invocation.getter(#errorMessage),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#errorMessage),
        ),
      ) as String);

  @override
  List<Map<String, dynamic>> get dateSuggestions => (super.noSuchMethod(
        Invocation.getter(#dateSuggestions),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  int get rhmScore => (super.noSuchMethod(
        Invocation.getter(#rhmScore),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProvider extends _i1.Mock implements _i9.UserProvider {
  MockUserProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setCurrentUser(_i10.UserModel? user) => super.noSuchMethod(
        Invocation.method(
          #setCurrentUser,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> fetchUserData() => (super.noSuchMethod(
        Invocation.method(
          #fetchUserData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateProfileImage(String? newImageUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfileImage,
          [newImageUrl],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.ImageProvider<Object>> getProfileImage() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileImage,
          [],
        ),
        returnValue: _i7.Future<_i3.ImageProvider<Object>>.value(
            _FakeImageProvider_1<Object>(
          this,
          Invocation.method(
            #getProfileImage,
            [],
          ),
        )),
      ) as _i7.Future<_i3.ImageProvider<Object>>);

  @override
  _i3.ImageProvider<Object> getProfileImageSync() => (super.noSuchMethod(
        Invocation.method(
          #getProfileImageSync,
          [],
        ),
        returnValue: _FakeImageProvider_1<Object>(
          this,
          Invocation.method(
            #getProfileImageSync,
            [],
          ),
        ),
      ) as _i3.ImageProvider<Object>);

  @override
  _i7.Future<_i3.ImageProvider<Object>> getPartnerProfileImage() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPartnerProfileImage,
          [],
        ),
        returnValue: _i7.Future<_i3.ImageProvider<Object>>.value(
            _FakeImageProvider_1<Object>(
          this,
          Invocation.method(
            #getPartnerProfileImage,
            [],
          ),
        )),
      ) as _i7.Future<_i3.ImageProvider<Object>>);

  @override
  _i3.ImageProvider<Object> getPartnerProfileImageSync() => (super.noSuchMethod(
        Invocation.method(
          #getPartnerProfileImageSync,
          [],
        ),
        returnValue: _FakeImageProvider_1<Object>(
          this,
          Invocation.method(
            #getPartnerProfileImageSync,
            [],
          ),
        ),
      ) as _i3.ImageProvider<Object>);

  @override
  _i7.Future<void> fetchPartnerData() => (super.noSuchMethod(
        Invocation.method(
          #fetchPartnerData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void listenToPartnerMood(String? partnerId) => super.noSuchMethod(
        Invocation.method(
          #listenToPartnerMood,
          [partnerId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopListeningToPartner() => super.noSuchMethod(
        Invocation.method(
          #stopListeningToPartner,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> authenticateWithSharedPreferences() => (super.noSuchMethod(
        Invocation.method(
          #authenticateWithSharedPreferences,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveUserIdToSharedPreferences(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserIdToSharedPreferences,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserData(Map<String, dynamic>? updatedFields) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserData,
          [updatedFields],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserMood(String? mood) => (super.noSuchMethod(
        Invocation.method(
          #updateUserMood,
          [mood],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteCurrentUserAccount(String? password) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCurrentUserAccount,
          [password],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateFcmToken(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #updateFcmToken,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> refreshFcmToken(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #refreshFcmToken,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> manuallyRefreshFcmToken() => (super.noSuchMethod(
        Invocation.method(
          #manuallyRefreshFcmToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<Map<String, dynamic>> checkFcmStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkFcmStatus,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> testFcmNotification() => (super.noSuchMethod(
        Invocation.method(
          #testFcmNotification,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendPushNotification(
    String? receiverId,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPushNotification,
          [
            receiverId,
            message,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> getCoupleId() => (super.noSuchMethod(
        Invocation.method(
          #getCoupleId,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserLocation(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserLocation,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String> generateAndAssignCoupleCode(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAndAssignCoupleCode,
          [userId],
        ),
        returnValue: _i7.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #generateAndAssignCoupleCode,
            [userId],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> updateUserLoveLanguage(String? loveLanguage) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserLoveLanguage,
          [loveLanguage],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserGender(_i10.Gender? gender) => (super.noSuchMethod(
        Invocation.method(
          #updateUserGender,
          [gender],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CoupleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoupleProvider extends _i1.Mock implements _i11.CoupleProvider {
  MockCoupleProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> connectWithPartnerCode(
    String? currentUserId,
    String? partnerCode,
    String? currentUserName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectWithPartnerCode,
          [
            currentUserId,
            partnerCode,
            currentUserName,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchPartnerUserData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #fetchPartnerUserData,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchCoupleAndPartnerData(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCoupleAndPartnerData,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isFirstToDisconnect(String? coupleId) => (super.noSuchMethod(
        Invocation.method(
          #isFirstToDisconnect,
          [coupleId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> disconnectFromPartner({
    required String? currentUserId,
    required String? coupleId,
    required String? senderName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #disconnectFromPartner,
          [],
          {
            #currentUserId: currentUserId,
            #coupleId: coupleId,
            #senderName: senderName,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isRelationshipInactive(String? coupleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #isRelationshipInactive,
          [coupleId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CheckInProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckInProvider extends _i1.Mock implements _i12.CheckInProvider {
  MockCheckInProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i13.CheckInModel> get checkInHistory => (super.noSuchMethod(
        Invocation.getter(#checkInHistory),
        returnValue: <_i13.CheckInModel>[],
      ) as List<_i13.CheckInModel>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  _i4.CheckInRepository get checkInRepository => (super.noSuchMethod(
        Invocation.getter(#checkInRepository),
        returnValue: _FakeCheckInRepository_2(
          this,
          Invocation.getter(#checkInRepository),
        ),
      ) as _i4.CheckInRepository);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<String?> createCheckIn(
    String? userId,
    String? coupleId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCheckIn,
          [
            userId,
            coupleId,
          ],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> fetchLatestPartnerInsight(
    String? currentUserId,
    String? partnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchLatestPartnerInsight,
          [
            currentUserId,
            partnerId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markInsightAsRead(
    String? currentUserId,
    String? checkInId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markInsightAsRead,
          [
            currentUserId,
            checkInId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> loadCheckIn(
    String? userId,
    String? checkInId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadCheckIn,
          [
            userId,
            checkInId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> completeCheckIn(
    String? userId,
    String? checkInId,
    String? coupleId,
    List<_i13.CheckInQuestion>? questions,
    Map<String, dynamic>? answers,
    String? partnerId, {
    dynamic Function(
      String,
      String,
    )? sendPushNotification,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeCheckIn,
          [
            userId,
            checkInId,
            coupleId,
            questions,
            answers,
            partnerId,
          ],
          {#sendPushNotification: sendPushNotification},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> shareInsights(
    String? userId,
    String? checkInId,
    List<String>? insights,
    String? coupleId, {
    String? partnerFirstName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareInsights,
          [
            userId,
            checkInId,
            insights,
            coupleId,
          ],
          {#partnerFirstName: partnerFirstName},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setReminder(
    String? userId,
    String? checkInId,
    bool? reminderSet,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReminder,
          [
            userId,
            checkInId,
            reminderSet,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>> getStats(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [userId],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i13.CheckInModel?> getLastCompletedCheckIn(
    String? userId, {
    String? partnerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastCompletedCheckIn,
          [userId],
          {#partnerId: partnerId},
        ),
        returnValue: _i7.Future<_i13.CheckInModel?>.value(),
      ) as _i7.Future<_i13.CheckInModel?>);

  @override
  _i7.Stream<_i14.QuerySnapshot<Map<String, dynamic>>> getUserCheckInsStream(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserCheckInsStream,
          [userId],
        ),
        returnValue:
            _i7.Stream<_i14.QuerySnapshot<Map<String, dynamic>>>.empty(),
      ) as _i7.Stream<_i14.QuerySnapshot<Map<String, dynamic>>>);

  @override
  void clearCurrentCheckIn() => super.noSuchMethod(
        Invocation.method(
          #clearCurrentCheckIn,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> generateInsights(
    _i13.CheckInModel? checkIn, {
    List<_i13.CheckInModel>? recentHistory,
    bool? forPartner = false,
    String? userName,
    String? partnerName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateInsights,
          [checkIn],
          {
            #recentHistory: recentHistory,
            #forPartner: forPartner,
            #userName: userName,
            #partnerName: partnerName,
          },
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i7.Future<void> shareFullCheckInWithPartner(
    String? userId,
    String? partnerId,
    String? checkInId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareFullCheckInWithPartner,
          [
            userId,
            partnerId,
            checkInId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void listenToLatestPartnerInsight(
    String? currentUserId,
    String? partnerId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToLatestPartnerInsight,
          [
            currentUserId,
            partnerId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> cancelCheckIn(
    String? userId,
    String? checkInId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelCheckIn,
          [
            userId,
            checkInId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> shareSelectedInsights({
    required String? userId,
    required String? partnerId,
    required String? coupleId,
    required List<String>? insights,
    required String? checkInId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareSelectedInsights,
          [],
          {
            #userId: userId,
            #partnerId: partnerId,
            #coupleId: coupleId,
            #insights: insights,
            #checkInId: checkInId,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SecretNoteProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecretNoteProvider extends _i1.Mock
    implements _i15.SecretNoteProvider {
  MockSecretNoteProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void listenForUnreadNotes(
    String? coupleId,
    String? currentUserId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #listenForUnreadNotes,
          [
            coupleId,
            currentUserId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> markNoteAsRead(String? noteId) => (super.noSuchMethod(
        Invocation.method(
          #markNoteAsRead,
          [noteId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendSecretNote({
    required String? coupleId,
    required String? senderId,
    required String? receiverId,
    required String? content,
    _i16.File? imageFile,
    _i16.File? audioFile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSecretNote,
          [],
          {
            #coupleId: coupleId,
            #senderId: senderId,
            #receiverId: receiverId,
            #content: content,
            #imageFile: imageFile,
            #audioFile: audioFile,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TipsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTipsProvider extends _i1.Mock implements _i17.TipsProvider {
  MockTipsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> initialize({
    required String? userId,
    required String? coupleId,
    required Map<String, dynamic>? userData,
    required Map<String, dynamic>? partnerData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #userId: userId,
            #coupleId: coupleId,
            #userData: userData,
            #partnerData: partnerData,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserContext({
    Map<String, dynamic>? userData,
    Map<String, dynamic>? partnerData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserContext,
          [],
          {
            #userData: userData,
            #partnerData: partnerData,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DateIdeaProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateIdeaProvider extends _i1.Mock implements _i18.DateIdeaProvider {
  MockDateIdeaProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i19.DateIdea> get favoriteIdeas => (super.noSuchMethod(
        Invocation.getter(#favoriteIdeas),
        returnValue: <_i19.DateIdea>[],
      ) as List<_i19.DateIdea>);

  @override
  set favoriteIdeas(List<_i19.DateIdea>? _favoriteIdeas) => super.noSuchMethod(
        Invocation.setter(
          #favoriteIdeas,
          _favoriteIdeas,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isFavoritesLoading => (super.noSuchMethod(
        Invocation.getter(#isFavoritesLoading),
        returnValue: false,
      ) as bool);

  @override
  set isFavoritesLoading(bool? _isFavoritesLoading) => super.noSuchMethod(
        Invocation.setter(
          #isFavoritesLoading,
          _isFavoritesLoading,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> get selectedLocations => (super.noSuchMethod(
        Invocation.getter(#selectedLocations),
        returnValue: <String>[],
      ) as List<String>);

  @override
  set selectedLocations(List<String>? _selectedLocations) => super.noSuchMethod(
        Invocation.setter(
          #selectedLocations,
          _selectedLocations,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedVibe(String? _selectedVibe) => super.noSuchMethod(
        Invocation.setter(
          #selectedVibe,
          _selectedVibe,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedBudget(String? _selectedBudget) => super.noSuchMethod(
        Invocation.setter(
          #selectedBudget,
          _selectedBudget,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedTime(String? _selectedTime) => super.noSuchMethod(
        Invocation.setter(
          #selectedTime,
          _selectedTime,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set generatedIdea(_i19.DateIdea? _generatedIdea) => super.noSuchMethod(
        Invocation.setter(
          #generatedIdea,
          _generatedIdea,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  set isLoading(bool? _isLoading) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          _isLoading,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentSuggestionId(String? _currentSuggestionId) => super.noSuchMethod(
        Invocation.setter(
          #currentSuggestionId,
          _currentSuggestionId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentSuggestionCoupleId(String? _currentSuggestionCoupleId) =>
      super.noSuchMethod(
        Invocation.setter(
          #currentSuggestionCoupleId,
          _currentSuggestionCoupleId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentSuggestionIdeaId(String? _currentSuggestionIdeaId) =>
      super.noSuchMethod(
        Invocation.setter(
          #currentSuggestionIdeaId,
          _currentSuggestionIdeaId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set fallbackMessage(String? _fallbackMessage) => super.noSuchMethod(
        Invocation.setter(
          #fallbackMessage,
          _fallbackMessage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get disposed => (super.noSuchMethod(
        Invocation.getter(#disposed),
        returnValue: false,
      ) as bool);

  @override
  set disposed(bool? _disposed) => super.noSuchMethod(
        Invocation.setter(
          #disposed,
          _disposed,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<Map<String, dynamic>> get suggestions => (super.noSuchMethod(
        Invocation.getter(#suggestions),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  bool get isStreamConnected => (super.noSuchMethod(
        Invocation.getter(#isStreamConnected),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void updateDependencies(_i20.DoneDatesProvider? doneDatesProvider) =>
      super.noSuchMethod(
        Invocation.method(
          #updateDependencies,
          [doneDatesProvider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToSuggestions(String? coupleId) => super.noSuchMethod(
        Invocation.method(
          #listenToSuggestions,
          [coupleId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> refreshSuggestions() => (super.noSuchMethod(
        Invocation.method(
          #refreshSuggestions,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void clearSuggestionTracking() => super.noSuchMethod(
        Invocation.method(
          #clearSuggestionTracking,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isCurrentSuggestion(String? ideaId) => (super.noSuchMethod(
        Invocation.method(
          #isCurrentSuggestion,
          [ideaId],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setCurrentSuggestion(
    String? suggestionId,
    String? coupleId,
    String? ideaId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setCurrentSuggestion,
          [
            suggestionId,
            coupleId,
            ideaId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void debugSuggestionState() => super.noSuchMethod(
        Invocation.method(
          #debugSuggestionState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> testStreamConnection() => (super.noSuchMethod(
        Invocation.method(
          #testStreamConnection,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i19.DateIdea?> getDateIdeaById(String? dateIdeaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDateIdeaById,
          [dateIdeaId],
        ),
        returnValue: _i7.Future<_i19.DateIdea?>.value(),
      ) as _i7.Future<_i19.DateIdea?>);

  @override
  _i7.Future<void> suggestDateIdeaToPartner({
    required _i19.DateIdea? idea,
    required String? coupleId,
    required String? currentUserId,
    required String? partnerId,
    required _i7.Future<void> Function(
      String,
      String,
    )? sendPushNotification,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #suggestDateIdeaToPartner,
          [],
          {
            #idea: idea,
            #coupleId: coupleId,
            #currentUserId: currentUserId,
            #partnerId: partnerId,
            #sendPushNotification: sendPushNotification,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markSuggestionAsDone(
    String? coupleId,
    String? suggestionId,
    String? currentUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markSuggestionAsDone,
          [
            coupleId,
            suggestionId,
            currentUserId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cancelSuggestion({
    required String? coupleId,
    required String? suggestionId,
    required String? currentUserId,
    required String? partnerId,
    required _i7.Future<void> Function(
      String,
      String,
    )? sendPushNotification,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelSuggestion,
          [],
          {
            #coupleId: coupleId,
            #suggestionId: suggestionId,
            #currentUserId: currentUserId,
            #partnerId: partnerId,
            #sendPushNotification: sendPushNotification,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void toggleLocation(String? location) => super.noSuchMethod(
        Invocation.method(
          #toggleLocation,
          [location],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectVibe(String? vibe) => super.noSuchMethod(
        Invocation.method(
          #selectVibe,
          [vibe],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectBudget(String? budget) => super.noSuchMethod(
        Invocation.method(
          #selectBudget,
          [budget],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectTime(String? time) => super.noSuchMethod(
        Invocation.method(
          #selectTime,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> generateDateIdea({
    required String? userId,
    required String? coupleId,
    _i3.BuildContext? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateDateIdea,
          [],
          {
            #userId: userId,
            #coupleId: coupleId,
            #context: context,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFilters({
    List<String>? locations,
    String? vibe,
    String? budget,
    String? time,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setFilters,
          [],
          {
            #locations: locations,
            #vibe: vibe,
            #budget: budget,
            #time: time,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> addFavorite(
    _i19.DateIdea? idea,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [
            idea,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeFavorite(
    String? ideaId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [
            ideaId,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchFavorites(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #fetchFavorites,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool isFavorite(String? ideaId) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [ideaId],
        ),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DynamicActionsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDynamicActionsProvider extends _i1.Mock
    implements _i21.DynamicActionsProvider {
  MockDynamicActionsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> recordPersonalJournalSaved() => (super.noSuchMethod(
        Invocation.method(
          #recordPersonalJournalSaved,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> recordSharedJournalSaved() => (super.noSuchMethod(
        Invocation.method(
          #recordSharedJournalSaved,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> recordMemoryUploaded() => (super.noSuchMethod(
        Invocation.method(
          #recordMemoryUploaded,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> recordMessageSent() => (super.noSuchMethod(
        Invocation.method(
          #recordMessageSent,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> recordEventAdded() => (super.noSuchMethod(
        Invocation.method(
          #recordEventAdded,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> recordQuestionAsked() => (super.noSuchMethod(
        Invocation.method(
          #recordQuestionAsked,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> recordBucketListItemAdded() => (super.noSuchMethod(
        Invocation.method(
          #recordBucketListItemAdded,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> recordDateDone() => (super.noSuchMethod(
        Invocation.method(
          #recordDateDone,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> recordCheckInCompleted() => (super.noSuchMethod(
        Invocation.method(
          #recordCheckInCompleted,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i22.QuickAction> getDynamicActions() => (super.noSuchMethod(
        Invocation.method(
          #getDynamicActions,
          [],
        ),
        returnValue: <_i22.QuickAction>[],
      ) as List<_i22.QuickAction>);

  @override
  _i7.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RhmDetailProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRhmDetailProvider extends _i1.Mock implements _i23.RhmDetailProvider {
  MockRhmDetailProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i24.RhmAction> get recentActions => (super.noSuchMethod(
        Invocation.getter(#recentActions),
        returnValue: <_i24.RhmAction>[],
      ) as List<_i24.RhmAction>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  int get userScore => (super.noSuchMethod(
        Invocation.getter(#userScore),
        returnValue: 0,
      ) as int);

  @override
  int get partnerScore => (super.noSuchMethod(
        Invocation.getter(#partnerScore),
        returnValue: 0,
      ) as int);

  @override
  int get totalActivityPoints => (super.noSuchMethod(
        Invocation.getter(#totalActivityPoints),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void initialize(
    String? coupleId,
    String? userId,
    String? partnerId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #initialize,
          [
            coupleId,
            userId,
            partnerId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
